//! Versioned Matrix bridge adapter protocol.

use std::{fmt, str::FromStr};

use inline_client::{
    AuthStartRequest, AuthStartResult, AuthVerifyRequest, ChatParticipantsPage,
    ChatParticipantsRequest, ClientErrorCategory, ClientEvent, ClientFailure, ClientStatus,
    ConnectRequest, CreateDmRequest, CreateReplyThreadRequest, CreateThreadRequest, CreatedChat,
    DeleteMessageRequest, DialogsPage, DialogsRequest, EditMessageRequest, EventReliability,
    HistoryPage, HistoryRequest, InlineId, MessageMutation, ReactRequest, ReadRequest,
    SendTextRequest, TypingRequest, UploadHandle, UploadRequest,
};
use serde::{Deserialize, Serialize};

/// Current bridge adapter command/event protocol version.
pub const PROTOCOL_VERSION: u16 = 1;

/// Version metadata returned by health/status endpoints.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProtocolInfo {
    /// Bridge adapter protocol version.
    pub protocol_version: u16,
    /// Linked `inline-client` crate version.
    pub client_version: String,
}

impl ProtocolInfo {
    /// Returns protocol metadata for the currently linked adapter/client.
    pub fn current() -> Self {
        Self {
            protocol_version: PROTOCOL_VERSION,
            client_version: inline_client::VERSION.to_owned(),
        }
    }
}

/// Adapter health response.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SidecarHealth {
    /// Whether the adapter process is reachable.
    pub ok: bool,
    /// Versioned adapter protocol information.
    pub protocol: ProtocolInfo,
    /// Current observed Inline client status.
    pub status: ClientStatus,
}

/// Status snapshot exposed through the bridge adapter protocol.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SidecarStatus {
    /// Versioned adapter protocol information.
    pub protocol: ProtocolInfo,
    /// Current Inline client status.
    pub status: ClientStatus,
    /// Optional redacted failure.
    pub failure: Option<ClientFailure>,
}

impl SidecarStatus {
    /// Creates a status snapshot from the current client handle state.
    pub fn current(status: ClientStatus, failure: Option<ClientFailure>) -> Self {
        Self {
            protocol: ProtocolInfo::current(),
            status,
            failure,
        }
    }

    /// Converts a native client status snapshot into the adapter protocol form.
    pub fn from_client(snapshot: inline_client::ClientStatusSnapshot) -> Self {
        Self::current(snapshot.status, snapshot.failure)
    }
}

/// Stable request ID supplied by the Go bridge or generated by HTTP wrappers.
#[derive(Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SidecarRequestId(String);

impl SidecarRequestId {
    /// Maximum request ID length in bytes.
    pub const MAX_LEN: usize = 128;

    /// Creates a validated request ID.
    pub fn try_new(value: impl AsRef<str>) -> Result<Self, RequestIdError> {
        let trimmed = value.as_ref().trim();
        if trimmed.is_empty() {
            return Err(RequestIdError::Empty);
        }
        if trimmed.len() > Self::MAX_LEN {
            return Err(RequestIdError::TooLong {
                len: trimmed.len(),
                max: Self::MAX_LEN,
            });
        }
        if trimmed.chars().any(|ch| ch.is_ascii_control()) {
            return Err(RequestIdError::ControlCharacter);
        }
        Ok(Self(trimmed.to_owned()))
    }

    /// Returns the request ID string.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for SidecarRequestId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("SidecarRequestId").field(&self.0).finish()
    }
}

impl fmt::Display for SidecarRequestId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

impl FromStr for SidecarRequestId {
    type Err = RequestIdError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::try_new(value)
    }
}

/// Request ID validation error.
#[derive(Clone, Debug, PartialEq, Eq, thiserror::Error)]
pub enum RequestIdError {
    /// Request ID was empty or whitespace-only.
    #[error("request ID must not be empty")]
    Empty,
    /// Request ID exceeded the public protocol limit.
    #[error("request ID is too long ({len} > {max})")]
    TooLong {
        /// Actual length in bytes.
        len: usize,
        /// Maximum allowed length in bytes.
        max: usize,
    },
    /// Request ID contained ASCII control characters.
    #[error("request ID must not contain ASCII control characters")]
    ControlCharacter,
}

/// Versioned adapter command request.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SidecarRequest {
    /// Adapter protocol version.
    pub protocol_version: u16,
    /// Request ID supplied by the caller.
    pub id: SidecarRequestId,
    /// Command payload.
    pub command: SidecarCommand,
}

impl SidecarRequest {
    /// Creates a request using the current protocol version.
    pub fn current(id: SidecarRequestId, command: SidecarCommand) -> Self {
        Self {
            protocol_version: PROTOCOL_VERSION,
            id,
            command,
        }
    }
}

/// Adapter command payload.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", content = "data", rename_all = "snake_case")]
#[non_exhaustive]
pub enum SidecarCommand {
    /// Send an Inline login code.
    AuthStart(AuthStartRequest),
    /// Verify an Inline login code and persist the resulting session.
    AuthVerify(AuthVerifyRequest),
    /// Resume a previously stored session, if available.
    Resume,
    /// Connect or reconnect the client.
    Connect(ConnectRequest),
    /// Logout the current account.
    Logout,
    /// Fetch current status.
    Status,
    /// Fetch dialogs.
    Dialogs(DialogsRequest),
    /// Fetch history for a chat.
    History(HistoryRequest),
    /// Fetch participants for a chat.
    ChatParticipants(ChatParticipantsRequest),
    /// Create or open a direct message chat.
    CreateDm(CreateDmRequest),
    /// Create a regular Inline thread chat.
    CreateThread(CreateThreadRequest),
    /// Create a child/reply Inline thread chat.
    CreateReplyThread(CreateReplyThreadRequest),
    /// Send a text message.
    SendText(SendTextRequest),
    /// Edit a message.
    EditMessage(EditMessageRequest),
    /// Delete or unsend a message.
    DeleteMessage(DeleteMessageRequest),
    /// Add or remove a reaction.
    React(ReactRequest),
    /// Mark messages read.
    Read(ReadRequest),
    /// Set typing state.
    Typing(TypingRequest),
    /// Upload and send media.
    Upload(UploadRequest),
}

impl SidecarCommand {
    /// Returns the stable command kind name.
    pub const fn kind(&self) -> &'static str {
        match self {
            Self::AuthStart(_) => "auth_start",
            Self::AuthVerify(_) => "auth_verify",
            Self::Resume => "resume",
            Self::Connect(_) => "connect",
            Self::Logout => "logout",
            Self::Status => "status",
            Self::Dialogs(_) => "dialogs",
            Self::History(_) => "history",
            Self::ChatParticipants(_) => "chat_participants",
            Self::CreateDm(_) => "create_dm",
            Self::CreateThread(_) => "create_thread",
            Self::CreateReplyThread(_) => "create_reply_thread",
            Self::SendText(_) => "send_text",
            Self::EditMessage(_) => "edit_message",
            Self::DeleteMessage(_) => "delete_message",
            Self::React(_) => "react",
            Self::Read(_) => "read",
            Self::Typing(_) => "typing",
            Self::Upload(_) => "upload",
        }
    }
}

/// Adapter auth verify result.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct AuthVerifySidecarResult {
    /// Verified Inline user ID.
    pub user_id: InlineId,
    /// Account/store namespace persisted by the native client.
    pub account_namespace: String,
    /// Updated adapter status after persisting the session.
    pub status: SidecarStatus,
}

impl From<inline_client::AuthVerifyResult> for AuthVerifySidecarResult {
    fn from(value: inline_client::AuthVerifyResult) -> Self {
        Self {
            user_id: value.user_id,
            account_namespace: value.account_namespace,
            status: SidecarStatus::from_client(value.status),
        }
    }
}

/// Successful adapter result payload.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", content = "data", rename_all = "snake_case")]
#[non_exhaustive]
pub enum SidecarResult {
    /// No payload.
    Empty,
    /// Protocol information.
    ProtocolInfo(ProtocolInfo),
    /// Status snapshot.
    Status(SidecarStatus),
    /// Auth start result.
    AuthStart(AuthStartResult),
    /// Auth verify result.
    AuthVerify(AuthVerifySidecarResult),
    /// Dialog page.
    Dialogs(DialogsPage),
    /// History page.
    History(HistoryPage),
    /// Chat participant snapshot.
    ChatParticipants(ChatParticipantsPage),
    /// Created or opened chat.
    CreatedChat(CreatedChat),
    /// Message mutation acknowledgement.
    Message(MessageMutation),
    /// Upload handle.
    Upload(UploadHandle),
}

/// Redacted adapter error payload.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SidecarError {
    /// Stable error category.
    pub category: ClientErrorCategory,
    /// Redacted message suitable for status output.
    pub message: String,
    /// Optional retry delay in seconds.
    pub retry_after_seconds: Option<u64>,
}

impl SidecarError {
    /// Creates a redacted adapter error.
    pub fn new(category: ClientErrorCategory, message: impl Into<String>) -> Self {
        Self {
            category,
            message: message.into(),
            retry_after_seconds: None,
        }
    }
}

impl From<ClientFailure> for SidecarError {
    fn from(failure: ClientFailure) -> Self {
        Self::new(failure.category, failure.message)
    }
}

/// Adapter command outcome.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "status", content = "data", rename_all = "snake_case")]
pub enum SidecarOutcome {
    /// Successful result.
    Ok(SidecarResult),
    /// Failed result.
    Error(SidecarError),
}

/// Versioned adapter command response.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SidecarResponse {
    /// Adapter protocol version.
    pub protocol_version: u16,
    /// Request ID this response belongs to.
    pub id: SidecarRequestId,
    /// Command outcome.
    pub outcome: SidecarOutcome,
}

impl SidecarResponse {
    /// Creates a successful response using the current protocol version.
    pub fn ok(id: SidecarRequestId, result: SidecarResult) -> Self {
        Self {
            protocol_version: PROTOCOL_VERSION,
            id,
            outcome: SidecarOutcome::Ok(result),
        }
    }

    /// Creates an error response using the current protocol version.
    pub fn error(id: SidecarRequestId, error: SidecarError) -> Self {
        Self {
            protocol_version: PROTOCOL_VERSION,
            id,
            outcome: SidecarOutcome::Error(error),
        }
    }
}

/// Versioned adapter event envelope.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SidecarEventEnvelope {
    /// Adapter protocol version.
    pub protocol_version: u16,
    /// Optional monotonically increasing adapter-local sequence.
    pub sequence: Option<u64>,
    /// Event delivery reliability class.
    pub reliability: EventReliability,
    /// Committed native client event.
    pub event: ClientEvent,
}

impl SidecarEventEnvelope {
    /// Creates an event envelope using the current protocol version.
    pub fn current(event: ClientEvent) -> Self {
        Self {
            protocol_version: PROTOCOL_VERSION,
            sequence: None,
            reliability: event.reliability(),
            event,
        }
    }

    /// Sets the adapter-local sequence.
    pub fn with_sequence(mut self, sequence: u64) -> Self {
        self.sequence = Some(sequence);
        self
    }
}

#[cfg(test)]
mod tests {
    use inline_client::{ExternalId, PeerRef, RandomId};

    use super::*;

    #[test]
    fn request_round_trips_as_tagged_json() {
        let req = SidecarRequest::current(
            SidecarRequestId::try_new("req-1").unwrap(),
            SidecarCommand::SendText(SendTextRequest {
                peer: PeerRef::Chat {
                    chat_id: InlineId::new(7),
                },
                text: "hello".to_owned(),
                external_id: Some(ExternalId::try_new("matrix-event", "$event").unwrap()),
                random_id: Some(RandomId::new(99)),
                reply_to_message_id: None,
            }),
        );

        let json = serde_json::to_value(&req).unwrap();
        assert_eq!(json["protocol_version"], PROTOCOL_VERSION);
        assert_eq!(json["command"]["type"], "send_text");

        let decoded: SidecarRequest = serde_json::from_value(json).unwrap();
        assert_eq!(decoded, req);
    }

    #[test]
    fn event_uses_client_event_reliability() {
        let event = ClientEvent::Typing {
            chat_id: InlineId::new(1),
            user_id: InlineId::new(2),
            is_typing: true,
        };

        let envelope = SidecarEventEnvelope::current(event).with_sequence(10);

        assert_eq!(envelope.protocol_version, PROTOCOL_VERSION);
        assert_eq!(envelope.sequence, Some(10));
        assert_eq!(envelope.reliability, EventReliability::BestEffort);
    }

    #[test]
    fn response_error_wraps_client_failure() {
        let failure = ClientFailure::new(ClientErrorCategory::AuthExpired, "relogin required");
        let response = SidecarResponse::error(
            SidecarRequestId::try_new("req-2").unwrap(),
            SidecarError::from(failure),
        );

        match response.outcome {
            SidecarOutcome::Error(error) => {
                assert_eq!(error.category, ClientErrorCategory::AuthExpired);
                assert_eq!(error.message, "relogin required");
            }
            SidecarOutcome::Ok(_) => panic!("expected error outcome"),
        }
    }
}
